[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { version = "^0.1" }
tokio = { version = "^1.0", features = ["full"] }
serde = { version = "^1.0", features = ["derive"] }
serde_json = { version = "^1.0" }

framework = { path = ".." }
