[workspace]
members = ["example"]

[package]
name = "framework"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "^1.0", default-features = false }
thiserror = { version = "^2.0", default-features = false }
